# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testrun.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 661, 201))
        self.groupBox.setObjectName("groupBox")
        self.Status = QtWidgets.QPushButton(self.groupBox)
        self.Status.setGeometry(QtCore.QRect(430, 10, 121, 61))
        self.Status.setObjectName("Status")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 61, 31))
        self.label_2.setObjectName("label_2")
        self.edit_port = QtWidgets.QTextEdit(self.groupBox)
        self.edit_port.setGeometry(QtCore.QRect(80, 70, 321, 41))
        self.edit_port.setReadOnly(False)
        self.edit_port.setObjectName("edit_port")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 31))
        self.label.setObjectName("label")
        self.edit_ip = QtWidgets.QTextEdit(self.groupBox)
        self.edit_ip.setGeometry(QtCore.QRect(80, 20, 321, 41))
        self.edit_ip.setReadOnly(False)
        self.edit_ip.setObjectName("edit_ip")
        self.servo_on = QtWidgets.QPushButton(self.groupBox)
        self.servo_on.setGeometry(QtCore.QRect(430, 130, 121, 61))
        self.servo_on.setObjectName("servo_on")
        self.connect_Button = QtWidgets.QPushButton(self.groupBox)
        self.connect_Button.setGeometry(QtCore.QRect(80, 120, 321, 41))
        self.connect_Button.setObjectName("connect_Button")
        self.Go_Home = QtWidgets.QPushButton(self.groupBox)
        self.Go_Home.setGeometry(QtCore.QRect(430, 70, 121, 61))
        self.Go_Home.setObjectName("Go_Home")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(670, 300, 331, 311))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(160, 160, 71, 61))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.Pitch_POS = QtWidgets.QTextEdit(self.groupBox_3)
        self.Pitch_POS.setEnabled(True)
        self.Pitch_POS.setGeometry(QtCore.QRect(230, 90, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Pitch_POS.setFont(font)
        self.Pitch_POS.setObjectName("Pitch_POS")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(160, 90, 71, 61))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.Yaw_POS = QtWidgets.QTextEdit(self.groupBox_3)
        self.Yaw_POS.setEnabled(True)
        self.Yaw_POS.setGeometry(QtCore.QRect(230, 160, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Yaw_POS.setFont(font)
        self.Yaw_POS.setObjectName("Yaw_POS")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(10, 170, 71, 61))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.Y_POS = QtWidgets.QTextEdit(self.groupBox_3)
        self.Y_POS.setEnabled(True)
        self.Y_POS.setGeometry(QtCore.QRect(70, 90, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Y_POS.setFont(font)
        self.Y_POS.setObjectName("Y_POS")
        self.X_POS = QtWidgets.QTextEdit(self.groupBox_3)
        self.X_POS.setEnabled(True)
        self.X_POS.setGeometry(QtCore.QRect(70, 20, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.X_POS.setFont(font)
        self.X_POS.setObjectName("X_POS")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(0, 90, 71, 61))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.Roll_POS = QtWidgets.QTextEdit(self.groupBox_3)
        self.Roll_POS.setEnabled(True)
        self.Roll_POS.setGeometry(QtCore.QRect(230, 20, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Roll_POS.setFont(font)
        self.Roll_POS.setObjectName("Roll_POS")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(0, 20, 71, 61))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.Z_POS = QtWidgets.QTextEdit(self.groupBox_3)
        self.Z_POS.setEnabled(True)
        self.Z_POS.setGeometry(QtCore.QRect(70, 160, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Z_POS.setFont(font)
        self.Z_POS.setObjectName("Z_POS")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(160, 20, 71, 61))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.Get_Position = QtWidgets.QPushButton(self.groupBox_3)
        self.Get_Position.setGeometry(QtCore.QRect(70, 230, 93, 61))
        self.Get_Position.setObjectName("Get_Position")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setGeometry(QtCore.QRect(670, 0, 331, 301))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(160, 20, 71, 61))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.B_POS = QtWidgets.QTextBrowser(self.groupBox_4)
        self.B_POS.setEnabled(True)
        self.B_POS.setGeometry(QtCore.QRect(230, 90, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.B_POS.setFont(font)
        self.B_POS.setObjectName("B_POS")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(160, 90, 71, 61))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(0, 160, 71, 61))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.L_POS = QtWidgets.QTextBrowser(self.groupBox_4)
        self.L_POS.setEnabled(True)
        self.L_POS.setGeometry(QtCore.QRect(70, 90, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.L_POS.setFont(font)
        self.L_POS.setObjectName("L_POS")
        self.S_POS = QtWidgets.QTextBrowser(self.groupBox_4)
        self.S_POS.setEnabled(True)
        self.S_POS.setGeometry(QtCore.QRect(70, 20, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.S_POS.setFont(font)
        self.S_POS.setObjectName("S_POS")
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(0, 90, 71, 61))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.T_POS = QtWidgets.QTextBrowser(self.groupBox_4)
        self.T_POS.setEnabled(True)
        self.T_POS.setGeometry(QtCore.QRect(230, 160, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.T_POS.setFont(font)
        self.T_POS.setObjectName("T_POS")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(0, 20, 71, 61))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.U_POS = QtWidgets.QTextBrowser(self.groupBox_4)
        self.U_POS.setEnabled(True)
        self.U_POS.setGeometry(QtCore.QRect(70, 160, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.U_POS.setFont(font)
        self.U_POS.setObjectName("U_POS")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(160, 160, 71, 61))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.Get_Pulse = QtWidgets.QPushButton(self.groupBox_4)
        self.Get_Pulse.setEnabled(True)
        self.Get_Pulse.setGeometry(QtCore.QRect(70, 230, 93, 61))
        self.Get_Pulse.setObjectName("Get_Pulse")
        self.R_POS = QtWidgets.QTextBrowser(self.groupBox_4)
        self.R_POS.setEnabled(True)
        self.R_POS.setGeometry(QtCore.QRect(230, 20, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.R_POS.setFont(font)
        self.R_POS.setObjectName("R_POS")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setEnabled(True)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 200, 661, 411))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(0, 210, 41, 31))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(0, 270, 41, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 31, 31))
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(0, 330, 51, 31))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(10, 90, 31, 31))
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(10, 150, 31, 31))
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.X_Decre = QtWidgets.QPushButton(self.groupBox_5)
        self.X_Decre.setEnabled(True)
        self.X_Decre.setGeometry(QtCore.QRect(150, 20, 91, 51))
        self.X_Decre.setObjectName("X_Decre")
        self.X_Incre = QtWidgets.QPushButton(self.groupBox_5)
        self.X_Incre.setEnabled(True)
        self.X_Incre.setGeometry(QtCore.QRect(50, 20, 91, 51))
        self.X_Incre.setObjectName("X_Incre")
        self.Distance_mm = QtWidgets.QSlider(self.groupBox_5)
        self.Distance_mm.setEnabled(True)
        self.Distance_mm.setGeometry(QtCore.QRect(250, 90, 221, 31))
        self.Distance_mm.setMinimum(-10000)
        self.Distance_mm.setMaximum(10000)
        self.Distance_mm.setSingleStep(1)
        self.Distance_mm.setPageStep(500)
        self.Distance_mm.setOrientation(QtCore.Qt.Horizontal)
        self.Distance_mm.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Distance_mm.setObjectName("Distance_mm")
        self.Roll_Incre = QtWidgets.QPushButton(self.groupBox_5)
        self.Roll_Incre.setEnabled(True)
        self.Roll_Incre.setGeometry(QtCore.QRect(50, 200, 91, 51))
        self.Roll_Incre.setObjectName("Roll_Incre")
        self.Roll_Decre = QtWidgets.QPushButton(self.groupBox_5)
        self.Roll_Decre.setEnabled(True)
        self.Roll_Decre.setGeometry(QtCore.QRect(150, 200, 91, 51))
        self.Roll_Decre.setObjectName("Roll_Decre")
        self.Pitch_Incre = QtWidgets.QPushButton(self.groupBox_5)
        self.Pitch_Incre.setEnabled(True)
        self.Pitch_Incre.setGeometry(QtCore.QRect(50, 260, 91, 51))
        self.Pitch_Incre.setObjectName("Pitch_Incre")
        self.Pitch_Decre = QtWidgets.QPushButton(self.groupBox_5)
        self.Pitch_Decre.setEnabled(True)
        self.Pitch_Decre.setGeometry(QtCore.QRect(150, 260, 91, 51))
        self.Pitch_Decre.setObjectName("Pitch_Decre")
        self.Z_Incre = QtWidgets.QPushButton(self.groupBox_5)
        self.Z_Incre.setEnabled(True)
        self.Z_Incre.setGeometry(QtCore.QRect(50, 140, 91, 51))
        self.Z_Incre.setObjectName("Z_Incre")
        self.Z_Decre = QtWidgets.QPushButton(self.groupBox_5)
        self.Z_Decre.setEnabled(True)
        self.Z_Decre.setGeometry(QtCore.QRect(150, 140, 91, 51))
        self.Z_Decre.setObjectName("Z_Decre")
        self.Y_Incre = QtWidgets.QPushButton(self.groupBox_5)
        self.Y_Incre.setEnabled(True)
        self.Y_Incre.setGeometry(QtCore.QRect(50, 80, 91, 51))
        self.Y_Incre.setObjectName("Y_Incre")
        self.Y_Decre = QtWidgets.QPushButton(self.groupBox_5)
        self.Y_Decre.setEnabled(True)
        self.Y_Decre.setGeometry(QtCore.QRect(150, 80, 91, 51))
        self.Y_Decre.setObjectName("Y_Decre")
        self.Yall_Decre = QtWidgets.QPushButton(self.groupBox_5)
        self.Yall_Decre.setEnabled(True)
        self.Yall_Decre.setGeometry(QtCore.QRect(150, 320, 91, 51))
        self.Yall_Decre.setObjectName("Yall_Decre")
        self.Yall_Incre = QtWidgets.QPushButton(self.groupBox_5)
        self.Yall_Incre.setEnabled(True)
        self.Yall_Incre.setGeometry(QtCore.QRect(50, 320, 91, 51))
        self.Yall_Incre.setObjectName("Yall_Incre")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(250, 30, 221, 41))
        self.label_29.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setGeometry(QtCore.QRect(250, 210, 221, 41))
        self.label_30.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.Distance_deg = QtWidgets.QSlider(self.groupBox_5)
        self.Distance_deg.setEnabled(True)
        self.Distance_deg.setGeometry(QtCore.QRect(250, 150, 221, 31))
        self.Distance_deg.setMinimum(-10000)
        self.Distance_deg.setMaximum(10000)
        self.Distance_deg.setSingleStep(1)
        self.Distance_deg.setPageStep(500)
        self.Distance_deg.setOrientation(QtCore.Qt.Horizontal)
        self.Distance_deg.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Distance_deg.setObjectName("Distance_deg")
        self.Speed_deg = QtWidgets.QSlider(self.groupBox_5)
        self.Speed_deg.setEnabled(True)
        self.Speed_deg.setGeometry(QtCore.QRect(250, 330, 221, 31))
        self.Speed_deg.setMinimum(0)
        self.Speed_deg.setMaximum(10000)
        self.Speed_deg.setSingleStep(10)
        self.Speed_deg.setPageStep(250)
        self.Speed_deg.setOrientation(QtCore.Qt.Horizontal)
        self.Speed_deg.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Speed_deg.setObjectName("Speed_deg")
        self.Speed_mm = QtWidgets.QSlider(self.groupBox_5)
        self.Speed_mm.setEnabled(True)
        self.Speed_mm.setGeometry(QtCore.QRect(250, 270, 221, 31))
        self.Speed_mm.setMaximum(10000)
        self.Speed_mm.setSingleStep(1)
        self.Speed_mm.setPageStep(250)
        self.Speed_mm.setOrientation(QtCore.Qt.Horizontal)
        self.Speed_mm.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Speed_mm.setObjectName("Speed_mm")
        self.Show_distance = QtWidgets.QTextEdit(self.groupBox_5)
        self.Show_distance.setEnabled(True)
        self.Show_distance.setGeometry(QtCore.QRect(480, 90, 51, 31))
        self.Show_distance.setAcceptDrops(True)
        self.Show_distance.setObjectName("Show_distance")
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setGeometry(QtCore.QRect(540, 90, 49, 31))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.Show_deg = QtWidgets.QTextEdit(self.groupBox_5)
        self.Show_deg.setEnabled(True)
        self.Show_deg.setGeometry(QtCore.QRect(480, 150, 51, 31))
        self.Show_deg.setObjectName("Show_deg")
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setGeometry(QtCore.QRect(540, 150, 49, 31))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.Show_speed_mm = QtWidgets.QTextEdit(self.groupBox_5)
        self.Show_speed_mm.setEnabled(True)
        self.Show_speed_mm.setGeometry(QtCore.QRect(480, 270, 51, 31))
        self.Show_speed_mm.setObjectName("Show_speed_mm")
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        self.label_33.setGeometry(QtCore.QRect(540, 270, 49, 31))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.Show_speed_deg = QtWidgets.QTextEdit(self.groupBox_5)
        self.Show_speed_deg.setEnabled(True)
        self.Show_speed_deg.setGeometry(QtCore.QRect(480, 330, 51, 31))
        self.Show_speed_deg.setObjectName("Show_speed_deg")
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setGeometry(QtCore.QRect(540, 330, 49, 31))
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setEnabled(True)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 810, 661, 141))
        self.groupBox_7.setObjectName("groupBox_7")
        self.Recieving_Byte = QtWidgets.QTextEdit(self.groupBox_7)
        self.Recieving_Byte.setGeometry(QtCore.QRect(10, 20, 1021, 161))
        self.Recieving_Byte.setObjectName("Recieving_Byte")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(1010, 0, 661, 611))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_28 = QtWidgets.QLabel(self.groupBox_6)
        self.label_28.setGeometry(QtCore.QRect(10, 20, 640, 480))
        self.label_28.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_28.setObjectName("label_28")
        self.Camera_On = QtWidgets.QPushButton(self.groupBox_6)
        self.Camera_On.setGeometry(QtCore.QRect(10, 530, 121, 61))
        self.Camera_On.setObjectName("Camera_On")
        self.Take_Calib = QtWidgets.QPushButton(self.groupBox_6)
        self.Take_Calib.setGeometry(QtCore.QRect(310, 530, 121, 61))
        self.Take_Calib.setObjectName("Take_Calib")
        self.YOLO_On = QtWidgets.QPushButton(self.groupBox_6)
        self.YOLO_On.setGeometry(QtCore.QRect(160, 530, 121, 61))
        self.YOLO_On.setObjectName("YOLO_On")
        self.Stop_Calib = QtWidgets.QPushButton(self.groupBox_6)
        self.Stop_Calib.setGeometry(QtCore.QRect(450, 530, 121, 61))
        self.Stop_Calib.setObjectName("Stop_Calib")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 610, 661, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(320, 80, 71, 61))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.Pitch = QtWidgets.QTextEdit(self.groupBox_2)
        self.Pitch.setEnabled(True)
        self.Pitch.setGeometry(QtCore.QRect(230, 80, 91, 61))
        self.Pitch.setObjectName("Pitch")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(160, 80, 71, 61))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.Yaw = QtWidgets.QTextEdit(self.groupBox_2)
        self.Yaw.setEnabled(True)
        self.Yaw.setGeometry(QtCore.QRect(390, 80, 91, 61))
        self.Yaw.setObjectName("Yaw")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(320, 20, 71, 61))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.Y = QtWidgets.QTextEdit(self.groupBox_2)
        self.Y.setEnabled(True)
        self.Y.setGeometry(QtCore.QRect(230, 20, 91, 61))
        self.Y.setObjectName("Y")
        self.X = QtWidgets.QTextEdit(self.groupBox_2)
        self.X.setEnabled(True)
        self.X.setGeometry(QtCore.QRect(70, 20, 91, 61))
        self.X.setObjectName("X")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(160, 20, 71, 61))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.Roll = QtWidgets.QTextEdit(self.groupBox_2)
        self.Roll.setEnabled(True)
        self.Roll.setGeometry(QtCore.QRect(70, 80, 91, 61))
        self.Roll.setObjectName("Roll")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(0, 20, 71, 61))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.Z = QtWidgets.QTextEdit(self.groupBox_2)
        self.Z.setEnabled(True)
        self.Z.setGeometry(QtCore.QRect(390, 20, 91, 61))
        self.Z.setObjectName("Z")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setEnabled(True)
        self.label_8.setGeometry(QtCore.QRect(0, 80, 71, 61))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(480, 20, 81, 61))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.Speed = QtWidgets.QTextEdit(self.groupBox_2)
        self.Speed.setEnabled(True)
        self.Speed.setGeometry(QtCore.QRect(560, 20, 91, 61))
        self.Speed.setObjectName("Speed")
        self.Go_Position = QtWidgets.QPushButton(self.groupBox_2)
        self.Go_Position.setEnabled(True)
        self.Go_Position.setGeometry(QtCore.QRect(560, 80, 93, 61))
        self.Go_Position.setObjectName("Go_Position")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(70, 150, 121, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(390, 150, 121, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(230, 150, 89, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(670, 610, 201, 341))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_35 = QtWidgets.QLabel(self.groupBox_8)
        self.label_35.setGeometry(QtCore.QRect(30, 50, 63, 20))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.groupBox_8)
        self.label_36.setGeometry(QtCore.QRect(10, 90, 71, 21))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_8)
        self.label_37.setGeometry(QtCore.QRect(20, 130, 63, 20))
        self.label_37.setObjectName("label_37")
        self.Connect_Arduino = QtWidgets.QPushButton(self.groupBox_8)
        self.Connect_Arduino.setGeometry(QtCore.QRect(30, 220, 141, 51))
        self.Connect_Arduino.setObjectName("Connect_Arduino")
        self.Grab = QtWidgets.QPushButton(self.groupBox_8)
        self.Grab.setGeometry(QtCore.QRect(30, 280, 141, 51))
        self.Grab.setObjectName("Grab")
        self.edit_port_com = QtWidgets.QTextEdit(self.groupBox_8)
        self.edit_port_com.setGeometry(QtCore.QRect(80, 50, 111, 31))
        self.edit_port_com.setReadOnly(False)
        self.edit_port_com.setObjectName("edit_port_com")
        self.edit_baud_rate = QtWidgets.QTextEdit(self.groupBox_8)
        self.edit_baud_rate.setGeometry(QtCore.QRect(80, 90, 111, 31))
        self.edit_baud_rate.setObjectName("edit_baud_rate")
        self.edit_angle = QtWidgets.QTextEdit(self.groupBox_8)
        self.edit_angle.setGeometry(QtCore.QRect(80, 130, 111, 31))
        self.edit_angle.setObjectName("edit_angle")
        self.Arduino_state = QtWidgets.QPushButton(self.groupBox_8)
        self.Arduino_state.setGeometry(QtCore.QRect(30, 170, 141, 41))
        self.Arduino_state.setObjectName("Arduino_state")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(890, 610, 351, 241))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_43 = QtWidgets.QLabel(self.groupBox_9)
        self.label_43.setGeometry(QtCore.QRect(10, 100, 71, 61))
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.Pitch_OBJ = QtWidgets.QTextEdit(self.groupBox_9)
        self.Pitch_OBJ.setEnabled(True)
        self.Pitch_OBJ.setGeometry(QtCore.QRect(240, 100, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Pitch_OBJ.setFont(font)
        self.Pitch_OBJ.setObjectName("Pitch_OBJ")
        self.Yaw_OBJ = QtWidgets.QTextEdit(self.groupBox_9)
        self.Yaw_OBJ.setEnabled(True)
        self.Yaw_OBJ.setGeometry(QtCore.QRect(240, 170, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Yaw_OBJ.setFont(font)
        self.Yaw_OBJ.setObjectName("Yaw_OBJ")
        self.label_39 = QtWidgets.QLabel(self.groupBox_9)
        self.label_39.setGeometry(QtCore.QRect(170, 30, 71, 61))
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.label_38 = QtWidgets.QLabel(self.groupBox_9)
        self.label_38.setGeometry(QtCore.QRect(170, 170, 71, 61))
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.Z_OBJ = QtWidgets.QTextEdit(self.groupBox_9)
        self.Z_OBJ.setEnabled(True)
        self.Z_OBJ.setGeometry(QtCore.QRect(80, 170, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Z_OBJ.setFont(font)
        self.Z_OBJ.setObjectName("Z_OBJ")
        self.Y_OBJ = QtWidgets.QTextEdit(self.groupBox_9)
        self.Y_OBJ.setEnabled(True)
        self.Y_OBJ.setGeometry(QtCore.QRect(80, 100, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Y_OBJ.setFont(font)
        self.Y_OBJ.setObjectName("Y_OBJ")
        self.label_42 = QtWidgets.QLabel(self.groupBox_9)
        self.label_42.setGeometry(QtCore.QRect(10, 170, 71, 61))
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.Roll_OBJ = QtWidgets.QTextEdit(self.groupBox_9)
        self.Roll_OBJ.setEnabled(True)
        self.Roll_OBJ.setGeometry(QtCore.QRect(240, 30, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Roll_OBJ.setFont(font)
        self.Roll_OBJ.setObjectName("Roll_OBJ")
        self.X_OBJ = QtWidgets.QTextEdit(self.groupBox_9)
        self.X_OBJ.setEnabled(True)
        self.X_OBJ.setGeometry(QtCore.QRect(80, 30, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.X_OBJ.setFont(font)
        self.X_OBJ.setObjectName("X_OBJ")
        self.label_40 = QtWidgets.QLabel(self.groupBox_9)
        self.label_40.setGeometry(QtCore.QRect(170, 100, 71, 61))
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupBox_9)
        self.label_41.setGeometry(QtCore.QRect(10, 30, 71, 61))
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.Pick_Place = QtWidgets.QPushButton(self.centralwidget)
        self.Pick_Place.setGeometry(QtCore.QRect(890, 870, 121, 61))
        self.Pick_Place.setObjectName("Pick_Place")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Connection"))
        self.Status.setText(_translate("MainWindow", "Status"))
        self.label_2.setText(_translate("MainWindow", "Port"))
        self.edit_port.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">10040</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "IP address"))
        self.edit_ip.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">192.168.1.12</span></p></body></html>"))
        self.servo_on.setText(_translate("MainWindow", "ServoOn"))
        self.connect_Button.setText(_translate("MainWindow", "Connection/Disconnect"))
        self.Go_Home.setText(_translate("MainWindow", "Go Home"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Get Cartaisan POS"))
        self.label_16.setText(_translate("MainWindow", "Yaw (deg)"))
        self.Pitch_POS.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "Picth (deg)"))
        self.Yaw_POS.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "Z (mm)"))
        self.Y_POS.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.X_POS.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0 </span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "Y (mm)"))
        self.Roll_POS.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "X (mm)"))
        self.Z_POS.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "Roll (deg)"))
        self.Get_Position.setText(_translate("MainWindow", "Get Position"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Get Pulse POS"))
        self.label_22.setText(_translate("MainWindow", "R (deg)"))
        self.B_POS.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "B (deg)"))
        self.label_24.setText(_translate("MainWindow", "U (deg)"))
        self.L_POS.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.S_POS.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "L (deg)"))
        self.T_POS.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "S (deg)"))
        self.U_POS.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "T (deg)"))
        self.Get_Pulse.setText(_translate("MainWindow", "Get Pulse"))
        self.R_POS.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Cartasian Incremental Move"))
        self.label_13.setText(_translate("MainWindow", "Roll"))
        self.label_3.setText(_translate("MainWindow", "Pitch"))
        self.label_11.setText(_translate("MainWindow", "X"))
        self.label_15.setText(_translate("MainWindow", "Yall"))
        self.label_14.setText(_translate("MainWindow", "Y"))
        self.label_12.setText(_translate("MainWindow", "z"))
        self.X_Decre.setText(_translate("MainWindow", "-"))
        self.X_Incre.setText(_translate("MainWindow", "+"))
        self.Roll_Incre.setText(_translate("MainWindow", "+"))
        self.Roll_Decre.setText(_translate("MainWindow", "-"))
        self.Pitch_Incre.setText(_translate("MainWindow", "+"))
        self.Pitch_Decre.setText(_translate("MainWindow", "-"))
        self.Z_Incre.setText(_translate("MainWindow", "+"))
        self.Z_Decre.setText(_translate("MainWindow", "-"))
        self.Y_Incre.setText(_translate("MainWindow", "+"))
        self.Y_Decre.setText(_translate("MainWindow", "-"))
        self.Yall_Decre.setText(_translate("MainWindow", "-"))
        self.Yall_Incre.setText(_translate("MainWindow", "+"))
        self.label_29.setText(_translate("MainWindow", "Distance"))
        self.label_30.setText(_translate("MainWindow", "Speed"))
        self.Show_distance.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.label_31.setText(_translate("MainWindow", " mm"))
        self.Show_deg.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.label_32.setText(_translate("MainWindow", " deg"))
        self.Show_speed_mm.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "mm"))
        self.Show_speed_deg.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "deg"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Recieving Byte"))
        self.groupBox_6.setTitle(_translate("MainWindow", "CAMERA"))
        self.label_28.setText(_translate("MainWindow", "TextLabel"))
        self.Camera_On.setText(_translate("MainWindow", "Camera_On"))
        self.Take_Calib.setText(_translate("MainWindow", "Take_Calib"))
        self.YOLO_On.setText(_translate("MainWindow", "YOLO_On"))
        self.Stop_Calib.setText(_translate("MainWindow", "Stop_Calib"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Cartasian Absolute Move"))
        self.label_10.setText(_translate("MainWindow", "Yaw (deg)"))
        self.Pitch.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2.271</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Picth (deg)"))
        self.Yaw.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">54.296</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Z (mm)"))
        self.Y.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-107.123</p></body></html>"))
        self.X.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">245.654</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Y (mm)"))
        self.Roll.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-1798.671</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "X (mm)"))
        self.Z.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-98.454</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "Roll (deg)"))
        self.label_9.setText(_translate("MainWindow", "Speed(%)"))
        self.Speed.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1000</p></body></html>"))
        self.Go_Position.setText(_translate("MainWindow", "Go Position"))
        self.radioButton.setText(_translate("MainWindow", "Cartasian Straight"))
        self.radioButton_2.setText(_translate("MainWindow", "Cartasian Link"))
        self.radioButton_3.setText(_translate("MainWindow", "Pulse Link"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Gripper"))
        self.label_35.setText(_translate("MainWindow", "Port"))
        self.label_36.setText(_translate("MainWindow", "Baud_rate"))
        self.label_37.setText(_translate("MainWindow", "Angle"))
        self.Connect_Arduino.setText(_translate("MainWindow", "Connect"))
        self.Grab.setText(_translate("MainWindow", "Grab"))
        self.edit_port_com.setMarkdown(_translate("MainWindow", "COM13\n"
"\n"
""))
        self.edit_port_com.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">COM13</p></body></html>"))
        self.edit_baud_rate.setMarkdown(_translate("MainWindow", "9600\n"
"\n"
""))
        self.edit_baud_rate.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">9600</p></body></html>"))
        self.Arduino_state.setText(_translate("MainWindow", "Status"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Object_Pos"))
        self.label_43.setText(_translate("MainWindow", "Y (mm)"))
        self.Pitch_OBJ.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.Yaw_OBJ.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "Roll (deg)"))
        self.label_38.setText(_translate("MainWindow", "Yaw (deg)"))
        self.Z_OBJ.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.Y_OBJ.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "Z (mm)"))
        self.Roll_OBJ.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.X_OBJ.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0 </span></p></body></html>"))
        self.label_40.setText(_translate("MainWindow", "Picth (deg)"))
        self.label_41.setText(_translate("MainWindow", "X (mm)"))
        self.Pick_Place.setText(_translate("MainWindow", "Pick_Place"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
